Update jekyll-gh-pages.yml

diff --git a/.github/workflows/jekyll-gh-pages.yml b/.github/workflows/jekyll-gh-pages.yml
--- a/.github/workflows/jekyll-gh-pages.yml
+++ b/.github/workflows/jekyll-gh-pages.yml
@@ -36,7 +36,7 @@ jobs:
           source: ./
           destination: ./_site
       - name: change index
-        run: cp ./_site/目录.html ./_site/index.html || echo "目录.html not found"
+        run: sudo cp ./_site/目录.html ./_site/index.html || echo "目录.html not found"
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
 
